services:
  frontend:
    image: bloglist-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # args:
      #   - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - backend
    container_name: bloglist-frontend

  backend:
    image: bloglist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
          PORT: ${PORT}
          SECRET: ${SECRET}
          MONGODB_URI: ${MONGODB_URI}
          TEST_MONGODB_URI: ${TEST_MONGODB_URI}
    volumes:
      - /usr/src/app/node_modules
    container_name: bloglist-backend


  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    container_name: reverse-proxy-blog