services:
  frontend:
    image: bloglist-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
      # args:
      #   - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    container_name: bloglist-frontend-dev

  backend:
    image: bloglist-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
      args:
          PORT: ${PORT}
          SECRET: ${SECRET}
          MONGODB_URI: ${MONGODB_URI}
          TEST_MONGODB_URI: ${TEST_MONGODB_URI}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: bloglist-backend-dev


  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    container_name: reverse-proxy-blog-dev